name: flutter_wordz2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  get_it: any
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  mockito: ^5.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/data/dictionary.json
